//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HAMBURGERDBEntities4 : DbContext
    {
        public HAMBURGERDBEntities4()
            : base("name=HAMBURGERDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLFIRSAT> TBLFIRSAT { get; set; }
        public virtual DbSet<TBLFIRSAT2> TBLFIRSAT2 { get; set; }
        public virtual DbSet<TBLFOOTER> TBLFOOTER { get; set; }
        public virtual DbSet<TBLGALERI> TBLGALERI { get; set; }
        public virtual DbSet<TBLGİRİS> TBLGİRİS { get; set; }
        public virtual DbSet<TBLMENU> TBLMENU { get; set; }
        public virtual DbSet<TBLYORUMLAR> TBLYORUMLAR { get; set; }
    }
}
