//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLABOUT
    {
        public int AboutID { get; set; }
        public string AboutBaslik { get; set; }
        public string AboutText { get; set; }
        public string AboutImageURL { get; set; }
    }
}
