//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFOOTER
    {
        public int FooterID { get; set; }
        public string FooterText { get; set; }
        public string FooterAcilisSattler { get; set; }
        public string FooterMail { get; set; }
        public string FotterTelefon { get; set; }
        public string FooterAdres { get; set; }
        public string FooterFacebook { get; set; }
        public string FooterTwitter { get; set; }
        public string Footerİnstagram { get; set; }
    }
}
