//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFIRSAT2
    {
        public int FirsatikiID { get; set; }
        public string FirsatikiBaslik { get; set; }
        public string Firsat2Fiyat { get; set; }
        public string FirsatikiAciklama1 { get; set; }
        public string FirsatikiAciklama2 { get; set; }
        public string FirsatikiAciklama3 { get; set; }
        public string FirsatArkaPlanRenk { get; set; }
        public string Durum { get; set; }
    }
}
