//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFIRSAT
    {
        public int FirsatID { get; set; }
        public string FirsatBaslik { get; set; }
        public string FirsatFiyat { get; set; }
        public string FirsatAciklama1 { get; set; }
        public string FirsatAciklama2 { get; set; }
        public string FirsatAciklama3 { get; set; }
        public string Renk { get; set; }
        public string Durum { get; set; }
    }
}
