//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGİRİS
    {
        public int GirisID { get; set; }
        public string GirisBaslik { get; set; }
        public string GirisTelefon { get; set; }
        public string GirisImageURL { get; set; }
    }
}
