//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYORUMLAR
    {
        public int YorumID { get; set; }
        public string YorumAdSoyad { get; set; }
        public string Email { get; set; }
        public string YorumText { get; set; }
        public Nullable<bool> YorumStatus { get; set; }
    }
}
